Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
list_


['1', '2', '3', '4', '5']

In [7]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


There is a difference in the data types of the variables. The list_ contains strings while array_list contains numpy array with data type inferred from the input (which in this case would be a string).

Q2.Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [9]:
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(item.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


In [10]:
array_list = np.array(object=list_, dtype=int)

Yes, there will be a difference in the data types of the elements. The elements in array_list will now have the data type int.

In [11]:
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(item.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
int64
int64
int64
int64
int64


Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [15]:
zero_array = np.zeros((3, 3))
print("\n Zero array: \n", zero_array)



 Zero array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
idnty_matrix = np.identity(5)
print("\n Identity matrix:\n", idnty_matrix)



 Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
